version: '3.8'

services:
  # LibreChat main application
  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: privae_librechat
    restart: unless-stopped
    ports:
      - "3026:3080"  # Map internal 3080 to external 3026
    depends_on:
      - mongodb
      - meilisearch
      - redis
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - DOMAIN_CLIENT=http://localhost:3026
      - DOMAIN_SERVER=http://localhost:3026
      - ENDPOINTS=ollama

      # Security
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}

      # Registration
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_REGISTRATION=true

      # Search
      - SEARCH=true
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-DevelopmentKey123456789}

      # Redis
      - USE_REDIS=true
      - REDIS_URI=redis://redis:6379

      # File uploads
      - ENABLE_AVATARS=true
      - ENABLE_FILE_UPLOADS=true

      # Logging
      - DEBUG_LOGGING=true
      - CONSOLE_JSON=false

    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - librechat_uploads:/app/client/public/images
      - librechat_logs:/app/api/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host Ollama
    networks:
      - privae-network

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: privae_mongodb
    restart: unless-stopped
    ports:
      - "27026:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=LibreChat
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: mongod --quiet --logpath /dev/null
    networks:
      - privae-network

  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: privae_meilisearch
    restart: unless-stopped
    ports:
      - "7726:7700"
    environment:
      - MEILI_HOST=http://0.0.0.0:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-DevelopmentKey123456789}
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data/meilisearch:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - privae-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: privae_redis
    restart: unless-stopped
    ports:
      - "6326:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - privae-network

volumes:
  librechat_uploads:
  librechat_logs:

networks:
  privae-network:
    driver: bridge
